Repository NachoXx25/Monolito-Modular, pull requests merged in 2025-04, with the labels that each got.

#8 Add an initial test video and refactor the get videos method
  Application/Services/Implements/VideoService.cs
  Infrastructure/Data/DataSeeders/DataSeeder.cs
  Infrastructure/Repositories/Implements/VideoRepository.cs
  Infrastructure/Repositories/Interfaces/IVideoRepository.cs
Labels: feat, refactor

#9 Set command time out 60 seconds for remote conections to the deployed databases
  Application/Services/Implements/UserService.cs
  Infrastructure/Repositories/Implements/UserRepository.cs
  Monolito Modular.postman_collection.json
  Program.cs
  obj/Debug/net9.0/Monolito-Modular.AssemblyInfo.cs
  obj/Debug/net9.0/Monolito-Modular.AssemblyInfoInputs.cache
Labels: refactor

#10 Add dockerfile and docker-compose.yaml file and update the postman collection with the environment url of render.
  Dockerfile
  Infrastructure/Data/DataSeeders/DataSeeder.cs
  Monolito Modular.postman_collection.json
  Program.cs
  docker-compose.yaml
  obj/Debug/net9.0/Monolito-Modular.AssemblyInfo.cs
  obj/Debug/net9.0/Monolito-Modular.AssemblyInfoInputs.cache
Labels: feat

#12 Update readme and .env example
  .env.example
  README.md
Labels: documentation
